"""
calibrate_thresholds — ONE-TIME calibration of per-provider map-matching thresholds.

For each provider it runs the route matcher across the available areas, pools the
`routes_summary`, and calls `network_matching.suggest_thresholds()` to recommend the
**Filter 1** (`resolve_routes`) thresholds. **Filter 2** (`min_edge_used_pct`) is a hand-set
policy gate, not derivable from `suggest_thresholds` (it lives on `routes_long`).

Writes `config/match_thresholds.yaml`. Run once; re-run to recalibrate.

    python scripts/calibrate_thresholds.py
    python scripts/calibrate_thresholds.py --areas sodermalm tartu --min-edge-used-pct 30
"""

from __future__ import annotations

import argparse
import sys
from datetime import datetime, timezone
from pathlib import Path

import duckdb
import geopandas as gpd
import pandas as pd

BASE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(BASE))

from scripts.route_match import run_match_routes
from network_matching import suggest_thresholds

DEFAULT_AREAS = ["sodermalm", "sundbyberg", "lidingo", "nacka", "tartu"]
PROVIDERS = {"mapbox": (), "tomtom": ("traffic_level",)}
DEFAULT_MIN_EDGE_USED_PCT = 30.0
_RESOLVE_ORDER = ("max_match_dist", "max_bearing_diff", "min_overlap_pct")


def _load_edges(db_path: Path) -> gpd.GeoDataFrame:
    con = duckdb.connect(str(db_path), read_only=True)
    con.execute("INSTALL spatial")
    con.execute("LOAD spatial")
    df = con.execute("SELECT edge_id, ST_AsText(geometry) w FROM driving.edges").df()
    con.close()
    return gpd.GeoDataFrame(df.drop(columns="w"),
                            geometry=gpd.GeoSeries.from_wkt(df["w"]), crs="EPSG:4326")


def pooled_routes_summary(provider, areas, db_dir, output_dir):
    frames = []
    for area in areas:
        db = Path(db_dir) / f"{area}.duckdb"
        seg_path = Path(output_dir) / f"{area}_traffic_{provider}.geojson"
        if not db.exists() or not seg_path.exists():
            print(f"  [skip] {provider}/{area}: missing db or segments")
            continue
        edges = _load_edges(db)
        seg = gpd.read_file(seg_path)
        rs, _rl, _seg = run_match_routes(edges, seg, extra_cols=PROVIDERS[provider])
        if rs is None:
            print(f"  [skip] {provider}/{area}: no usable segments")
            continue
        print(f"  {provider}/{area}: routes_summary={len(rs):,}")
        frames.append(rs)
    return pd.concat(frames, ignore_index=True) if frames else None


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--areas", nargs="+", default=DEFAULT_AREAS)
    ap.add_argument("--db-dir", default="db")
    ap.add_argument("--output-dir", default="output")
    ap.add_argument("--min-edge-used-pct", type=float, default=DEFAULT_MIN_EDGE_USED_PCT)
    ap.add_argument("--out", default="config/match_thresholds.yaml")
    args = ap.parse_args()

    result = {}
    for provider in PROVIDERS:
        print(f"\n=== calibrating {provider} ===")
        rs = pooled_routes_summary(provider, args.areas, args.db_dir, args.output_dir)
        if rs is None:
            print(f"  no data for {provider}; skipping")
            continue
        rec = suggest_thresholds(rs, report=False)["recommended"]
        seg_match = {k: round(float(v), 3) for k, v in rec.items() if v is not None}
        result[provider] = {"segment_match": seg_match,
                            "min_edge_used_pct": args.min_edge_used_pct}
        print(f"  -> segment_match: {seg_match}")

    stamp = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines = [
        "# Per-provider map-matching thresholds for scripts/route_match.py.",
        f"# Auto-generated by scripts/calibrate_thresholds.py on {stamp}",
        f"# Calibrated on areas: {', '.join(args.areas)}",
        "# Filter 1 (segment_match): network_matching.suggest_thresholds(routes_summary) -> resolve_routes kwargs.",
        "# Filter 2 (min_edge_used_pct): hand-set policy = min % of the OSM edge the winning segment must use.",
        "# Re-run scripts/calibrate_thresholds.py to recalibrate; per-area *_traffic.yaml keys override these.",
        "",
    ]
    for provider, blk in result.items():
        lines.append(f"{provider}:")
        lines.append("  segment_match:")
        for k in _RESOLVE_ORDER:
            if k in blk["segment_match"]:
                lines.append(f"    {k}: {blk['segment_match'][k]}")
        lines.append(f"  min_edge_used_pct: {blk['min_edge_used_pct']}")
        lines.append("")

    out = BASE / args.out
    out.write_text("\n".join(lines))
    print(f"\nwrote {out}")


if __name__ == "__main__":
    main()
